export default[
	{'shape':['shape','型狀','型状']},
	{'imageLink':['imageLink','圖像','图像']},
	{'price':['price','價格','价格']},
	{'weight':['weight','重量','重量']},
	{'color':['color','顏色','颜色']},
	{'clarity':['clarity','淨度','净度']},
	{'cut':['cut','切工','切工']},
	{'polish':['polish','打磨','打磨']},
	{'symmetry':['symmetry','對稱','对称']},
	{'fluorescence':['fluorescence','螢光','荧光']},
	{'certificate':['certificate','證書編號','证书编号']},
	{'lab':['lab','檢驗中心','检验中心']},
	{'fluorescence':['fluorescence','螢光','荧光']},
	{'location':['status','狀態','状态']},
	{'stock no':['stock no','貨號','货号']},
	{'has_image':['has_image','圖像','图像']},

	{'RD':['RD','圓形','圆形']},
	{'Round':['Round','Round','Round']},
	{'ROUND':['Round','Round','Round']},
	{'PS':['PS','梨形','梨形']},
	{'Pear':['Pear','Pear','Pear']},
	{'PEAR':['Pear','Pear','Pear']},
	{'EM':['EM','祖母綠形','祖母绿形']},
	{'Emerald':['Emerald','Emerald','Emerald']},
	{'EMERALD':['Emerald','Emerald','Emerald']},
	{'PR':['PR','公主方形','公主方形']},
	{'Princess':['Princess','Princess','Princess']},
	{'PRINCESS':['Princess','Princess','Princess']},
	{'MQ':['MQ','馬眼形','马眼形']},
	{'Marquise':['Marquise','Marquise','Marquise']},
	{'MARQUISE':['Marquise','Marquise','Marquise']},
	{'CU':['CU','枕形','枕形']},
	{'Cushion':['Cushion','Cushion','Cushion']},
	{'CUSHION':['Cushion','Cushion','Cushion']},
	{'AC':['AC','上丁方形','上丁方形']},
	{'Asscher':['Asscher','Asscher','Asscher']},
	{'ASSCHER':['Asscher','Asscher','Asscher']},
	{'OV':['OV','橢圓形','椭圆形']},
	{'Oval':['Oval','Oval','Oval']},
	{'OVAL':['Oval','Oval','Oval']},
	{'HT':['HT','心形','心形']},
	{'Heart':['Heart','Heart','Heart']},
	{'HEART':['Heart','Heart','Heart']},
	{'RA':['RA','雷地恩形','雷地恩形']},
	{'Radiant':['Radiant','Radiant','Radiant']},
	{'RADIANT':['Radiant','Radiant','Radiant']},

	{'carat':['carat','重量','重量']},
	{'diamond':['diamond','鑽石','钻石']},
	{'Diamond':['Diamond','鑽石','钻石']},
	{'your name':['your name','提供名字','提供名字']},
	{'your Phone No.':['your Phone No.','提供電話號碼','提供电话号码']},	
	{'Appointment':['Appointment','預約','预约']},
	{'Details fo Appointment':['Details fo Appointment','預約細節','预约细节']},
	{'Contact Us':['Contact Us','聯絡我們','联络我们']},

	{'Very Good':['VG','VG','VG']},
	{'Good':['GD','GD','GD']},
	{'Excellent':['EX','EX','EX']},
	{'VG':['VG','VG','VG']},
	{'GD':['GD','GD','GD']},
	{'EX':['EX','EX','EX']},

	{'NoneCut':[' ',' ',' ']},
	{'NONE':['NONE','無','无']},
	{'None':['None','無','无']},
	{'NON':['NON','無','无']},
	{'FAINT':['FAINT','微','微']},
	{'Faint':['Faint','微','微']},
	{'FNT':['FNT','微','微']},
	{'Fnt':['Fnt','微','微']},
	{'MEDIUM':['MEDIUM','中度','中度']},
	{'Medium':['Medium','中度','中度']},
	{'MED':['MED','中度','中度']},
	{'Med':['Med','中度','中度']},
	{'STRONG':['STRONG','強','強']},
	{'Strong':['Strong','強','強']},
	{'Very Strong':['Very Strong','非常強','非常強']},
	{'VST':['Very Strong','非常強','非常強']},
	{'STR':['STR','強','強']},
	{'STG':['STG','強','強']},
	{'Order':['Order','需預訂','需预订']},
	
	{'Carat Diamond Ring':['Carat Diamond Ring','卡鑽石戒指','卡钻石戒指']},
	{'fancy diamond':['fancy diamond','彩色鑽石','彩色钻石']},
	{'Fancy Diamond':['Fancy Diamond','彩色鑽石','彩色钻石']},
	{'Only On Stock':['Only On Stock','只選現貨','只選現貨']},
	
	
	{'True':['Yes','是','是']},
	{'False':['No','否','否']},
	{'Yes':['Yes','是','是']},
	{'1':['Yes','是','是']},
	{'No':['No','否','否']},	
	{'0':['No','否','否']},
]