export default[
	{'Solitaire':['Solitaire','單石','单石']},
	{'solitaire':['Solitaire','單石','单石']},	
	{'Side-stone':['Side-stone','輔石','辅石',]},
	{'side-stone':['Side-stone','輔石','辅石']},
	{'sideStone':['side-stone','輔石','辅石']},
	{'ct':['ct','重量','重量']},	
	{'Halo':['Halo','圍圈','围圈']},
	{'halo':['Halo','圍圈','围圈']},
	{'4-claw prong':['4-prong', '四爪', '四爪']},
	{'4-prong':['4-prong', '四爪', '四爪']},
	{'6-claw prong':['6-prong','六爪','六爪']},
	{'6-prong':['6-prong','六爪','六爪']},

	{'Tapering':['Tapering', '尖臂', '尖臂']},
	{'tapering':['Tapering', '尖臂', '尖臂']},
	{'Parallel':['Parallel', '平臂', '平臂']},
	{'parallel':['Parallel', '平臂', '平臂']},
	{'Twisted':['Twisted', '扭臂', '扭臂']},
	{'twisted':['Twisted', '扭臂', '扭臂']},

	{'prong':['prong','爪數','爪数']},
	{'unit_price':['unit_price', '價格', '价格']},
	{'Shoulder':['Shoulder', '臂', '臂']},
	{'shoulder':['shoulder', '臂位', '臂位']},
	{'stock':['stock','輔鑽石','辅钻石']},
	{'name':['name','名稱','名称']},
	{'description':['description','名稱','名称']},

	{'engagementRing':['Engagement Ring','求婚戒指','求婚戒指']},
	{'Ring':['Ring','戒指','戒指']},
	{'ring':['ring','戒指','戒指']},
	{'Engagement Ring':['Engagement Ring','求婚戒指','求婚戒指']},
	{'Engagement Ring Setting':['Engagement Ring Setting','求婚戒指托','求婚戒指托']},
	{'your name':['your name','客人稱呼','客人称呼']},
	{'your Phone No.':['your Phone No.','客人電話號碼','客人电话号码']},	
	{'Appointment':['Appointment','請預約','请预约']},
	{'Details fo Appointment':['Details fo Appointment','預約詳情','预约详情']},
	{'Contact Us':['Contact Us','聯絡我們','联络我们']},

	{'Review':['Review','完成','完成']},


	{'undefined':['undefined','undefined','undefined']},
	{'True':['Yes','是','是']},
	{'False':['No','否','否']},
	{'Yes':['Yes','是','是']},
	{'1':['Yes','是','是']},
	{'No':['No','否','否']},	
	{'0':['No','否','否']},
]