export default[
	{'EN':['EN','配飾','配飾']},
	{'HK':['HK','配飾','配飾']},
	{'CN':['CN','配飾','配飾']},
	{'Round Diamonds':['Round Diamonds','配飾','配飾']},
	{'Fancy Cut Diamonds':['Fancy Cut Diamonds','配飾','配飾']},
	{'Fancy Color Diamonds':['Fancy Color Diamonds','配飾','配飾']},
	{'Diamonds':['Diamonds','配飾','配飾']},
	{'Diamond':['Diamond','配飾','配飾']},
	{'diamond':['diamond','配飾','配飾']},
	{'Ring':['Ring','配飾','配飾']},
	{'Solitaire Ring':['Solitaire Ring','配飾','配飾']},
	{'Side-stone Ring':['Side-stone Ring','配飾','配飾']},
	{'Halo Ring':['Halo Ring','配飾','配飾']},
	{'Engagement Rings':['Engagement Rings','配飾','配飾']},
	{'Wedding Rings':['Wedding Rings','配飾','配飾']},
	{'Buying Procedure':['Buying Procedure','配飾','配飾']},
	{'Education':['Education','配飾','配飾']},
	{'Customer Moments':['Customer Moments','配飾','配飾']},
	{'About Us':['About Us','配飾','配飾']},
	{'Language':['Language','配飾','配飾']},
	{'Classic Ring':['Classic Ring','配飾','配飾']},
	{'Japanese Ring':['Japanese Ring','配飾','配飾']},
	{'Vintage Ring':['Vintage Ring','配飾','配飾']},
	{'Customer Jewelleries':['Customer Jewelleries','配飾','配飾']},
	{'Customer Jewellery':['Customer Jewellery','配飾','配飾']},
	{'Engagement Tips':['Engagement Tips','配飾','配飾']},
	{'Diamond Grading':['Diamond Grading','配飾','配飾']},
	{'Diamond Certficate':['Diamond Certficate','配飾','配飾']},
	{'Diamond Anatomy':['Diamond Anatomy','配飾','配飾']},
	{'Fancy Color Diamond':['Fancy Color Diamond','配飾','配飾']},
	{'Carat':['Carat','配飾','配飾']},
	{'Cut':['Cut','配飾','配飾']},
	{'Color':['Color','配飾','配飾']},
	{'Clarity':['Clarity','配飾','配飾']},
	{'Diamond Certificate':['Diamond Certificate','配飾','配飾']},
	{'GIA Report':['GIA Report','配飾','配飾']},
	{'Eye Clean Diamond':['Eye Clean Diamond','配飾','配飾']},
	{'Diamond Anatomy':['Diamond Anatomy','配飾','配飾']},
	{'Certificate':['Certificate','配飾','配飾']},
	{'Shape':['Shape','配飾','配飾']},
	{'Heards And Arrows':['Heards And Arrows','配飾','配飾']},
	{'Proportion':['Proportion','配飾','配飾']},
	{'Symmetry':['Symmetry','配飾','配飾']},
	{'Polish':['Polish','配飾','配飾']},
	{'Fluorescence':['Fluorescence','配飾','配飾']},
	{'Customer Jewellries':['Customer Jewellries','配飾','配飾']},

	
]