export default[
	{'Accessory':['Accessory','配飾','配飾']},
	{'Bracelet':['Bracelet','手鍊','手链']},
	{'Bracelet Setting':['Bracelet Setting','手鍊托','手链托']},
	{'Necklace':['Necklace','項鍊','项链']},
	{'Necklace Setting':['Necklace Setting','項鍊托','项链托']},
	{'Earring':['Earring','耳環','耳环']},
	{'Earring Setting':['Earring Setting','耳環托','耳环托']},
	{'Pendant':['Pendant','吊咀','吊坠']},
	{'Pendant Setting':['Pendant Setting','吊咀托','吊坠托']},
	{'Ring':['Ring','戒指','戒指']},
	{'Misc':['Misc','Misc','Misc']},

	{'':['', '', '']},
	
	{'unit_price':['unit_price', '價格','价格']},
	{'metal':['metal', '金屬', '金属']},
	{'type':['type', '款式', '款式']},
	{'gemstone':['gemstone', '寶石', '寶石']},
	{'setting':['setting', '托', '托']},
	{'sideStone':['side stone','輔石','辅石']},
	{'stock':['stock','款號','款号']},
	{'name':['name','名稱','名称']},
	{'description':['description','詳情描述','详情描述']},

	{'ct':['ct', '重量', '重量']},	
	{'Wedding Ring':['Wedding Ring','結婚對戒','结婚对戒']},
	{'your name':['your name','客人稱呼','客人称呼']},
	{'your Phone No.':['your Phone No.','客人電話號碼','客人电话号码']},	
	{'Appointment':['Appointment','請預約','请预约']},
	{'Details fo Appointment':['Details fo Appointment','預約詳情','预约详情']},
	{'Contact Us':['Contact Us','聯絡我們','联络我们']},

	{'jewellery':['jewellery', '首飾', '首饰']},
	{'Pearl':['Pearl', '珍珠', '珍珠']},
	{'pearl':['pearl', '珍珠', '珍珠']},

	{'True':['Yes','是','是']},
	{'False':['No','否','否']},
	{'Yes':['Yes','是','是']},
	{'1':['Yes','是','是']},
	{'No':['No','否','否']},	
	{'0':['No','否','否']},
	{'doesntHave':['No','無','無']},
	
]