export default[

	{'Select this Item':['Select this Item','選擇商品','选择商品']},
	{'message':['message','信息','信息']},
	{'same diamond on the list':['same diamond on the list','相同商品已在購物車中','相同商品已在购物车中']},
	{'find other diamond':['find other diamond','尋找其他鑽石','寻找其他钻石']},
	{'diamonds':['diamonds','鑽石','钻石']},
	{'engagementRings':['engagementRings','求婚戒指','求婚戒指']},
	{'Back to':['Back to','回到','回到']},
	{'Remove':['Remove','刪除','删除']},
	{'Ring Size':['Ring Size','戒指號','戒指号']},
	{'Engrave':['Engrave','刻字','刻字']},
	{'change':['change','更改','更改']},
	{'Apply Coupon':['Apply Coupon','使用優惠碼','使用优惠码']},
	{'Enter Coupon Code':['Enter Coupon Code','輸入優惠碼','输入优惠码']},
	{'Total':['Total','總數','总数']},
	{'Deposit (20%)':['Deposit (20%)','訂金(20%)','订金(20%)']},
	{'Balance (80%)':['Balance (80%)','餘額(80%)','余额(80%)']},
	{'VISA':['VISA/Master','VISA/Master','VISA/Master']},
	{'ESP(-1%)':['ESP(-1%)','ESP(-1%)','ESP(-1%)']},
	{'Alipay(-1%)':['Alipay(-1%)','支付寶(-1%)','支付宝(-1%)']},
	{'Wechat(-1%)':['Wechat(-1%)','微信(-1%)','微信(-1%)']},
	{'Cash(-2%)':['Cash(~1.7-2%)','現金(~1.7-2%)','现金(~1.7-2%)']},
	{'checkout':['checkout','結賬','结账']},

	{'Name':['Name',' 名稱',' 名称']},
	{'Mobile':['Mobile','電話號碼','电话号码']},
	{'Address':['Address','地址','地址']},
	{'Email':['Email','電郵地址','电邮地址']},
	{'Area':['Area','地區','地区']},
	{'HK':['HK','香港','香港']},
	{'CN':['CN','中國','中国']},

	{'Add A Diamond':['Add A Diamond','加入鑽石','加入钻石']},
	{'Add A Engagement Ring':['Add A Engagement Ring','加入戒指款式','加入戒指款式']},
	{'Add To Cart':['Add To Cart','加入購物車','加入购物车']},
	{'Disounted Total':['Disounted Total','折扣總數','折扣总数']},
	{'you only need to pay deposit, balance will pay after 100% satisfied':['you only need to pay deposit, balance will pay after 100% satisfied','只需先付定金，餘額在滿意成品後才付款','只需先付定金，余额在满意成品后才付款']},
	{'Today Order, Diamond Gets Free shipment':['Today Order, Diamond Gets Free shipment','今天下單, 鑽石免費運送','今天下单, 钻石免费运送']},
	{'On':['On','於','於']},
	{'check your pending order':['check your pending order','查看你的待確認訂單','查看你的待确认订单']},


	{'0':['No','否','否']},
	{'1':['Yes','是','是']},

	{'January':['January','1月','1月']},
	{'February':['February','2月','2月']},
	{'March':['March','3月','3月']},
	{'April':['April','四4','4月']},
	{'May':['May','5月','5月']},
	{'June':['June','6月','6月']},
	{'July':['July','7月','7月']},
	{'August':['August','8月','8月']},
	{'September':['September','9月','9月']},
	{'October':['October','10月','10月']},
	{'November':['November','11月','11月']},
	{'December':['December','12月','12月']},
	
	{'Sunday':['Sunday','星期日','星期日']},
	{'Monday':['Monday','星期一','星期一']},
	{'Tuesday':['Tuesday','星期二','星期二']},
	{'Wednesday':['Wednesday','星期三','星期三']},
	{'Thursday':['Thursday','星期四','星期四']},
	{'Friday':['Friday','星期五','星期五']},
	{'Saturday':['Saturday','星期六','星期六']},
	{'day':['','日','日']},

	{'Precautions':['Precautions','注意事項','注意事项']},
	{'All amounts of the company are subject to Hong Kong dollar settlement':['All amounts of the company are subject to Hong Kong dollar settlement','本公司一切金額以港幣結算為準 (我們8萬塊以上已經是現金價，在本公司鑲嵌戒指托，可以有1.7-2%左右優惠，如果需要付支付寶/微信, 或是刷卡, 需要付手續費的 )','本公司一切金额以港币结算为准（我们8万块以上已经是现金价，在本公司镶嵌戒指托，可以有1.7-2%左右优惠，如果需要付支付宝/微信，要么刷卡，需要付手续费的）']},
	{'The customer is required to pay the full amount and withdraw the goods within two months after the order is placed, otherwise the company reserves the right to terminate the transaction.':['The customer is required to pay the full amount and withdraw the goods within two months after the order is placed, otherwise the company reserves the right to terminate the transaction.','客戶需在訂貨後一個月內付完全額並提取貨物，否則本公司保留終止交易的權利。','客户需在订货一个月内付完全额并提取货物，否则本公司保留终止交易的权利。']},
	{'In order to protect the interests of both parties, unless the diamond does not match the GIA report, the order will not be returned after confirmation.':['In order to protect the interests of both parties, unless the diamond does not match the GIA report, the order will not be returned after confirmation.','為保障雙方利益, 除非鑽石跟GIA報告不相符，否則確認訂單後恕不退換。','为保障双方利益, 除非钻石跟GIA报告不相符，否则确认订单后恕不退换。']},
	{'The deposit amount is 20%, ranging from at least $ 3000 to at most $ 10,000.':['The deposit amount is 20%, ranging from at least $ 3000 to at most $ 10,000.','訂金數目為2成，由最少$3000到最多$10000。','订金数量为2成，由最少$ 3000到最多$ 10000。']},
	{'We buy directly in foreign countries, and it takes about 4-5 working days to ship to Hong Kong ~':['We buy directly in foreign countries, and it takes about 4-5 working days to ship to Hong Kong ~','我們直接在外國全數購買,運到香港需時4-5個工作天左右~','我们直接在外国全数购买,运到香港需时4-5个工作天左右~']},
	{'After the diamond arrives in Hong Kong, I will inform you ~ Provide photos and certificate physical map, and then pay the balance when you pick up the goods':['After the diamond arrives in Hong Kong, I will inform you ~ Provide photos and certificate physical map, and then pay the balance when you pick up the goods','鑽石運到香港後，我會通知你~提供相片同證書實物圖,然後你取貨時先付餘款','钻石运到香港后，我会通知你~提供相片同证书实物图,然后你取货时先付余款']},

	{'Login to save coupon code':['Login to save coupon code','登入賬號,儲存優惠碼','登入賬號,儲存優惠碼']},

	{'mounting fee':['mounting fee','鑲工','镶工']},
	
]