export default[
	{'Classic':['Classic','經典款式','经典款式']},
	{'classic':['Classic','經典款式','经典款式']},
	{'Japanese':['Japanese', '日本款', '日本款']},
	{'japanese':['Japanese', '日本款', '日本款']},
	{'Vintage':['Vintage', '歐洲款', '欧洲款']},
	{'vintage':['Vintage', '歐洲款', '欧洲款']},
	{'japan':['japan', '日本', '日本']},
	{'straight':['straight', '直身', '直身']},
	{'v-shape':['v-shape', 'V形', 'V形']},
	{'wave':['wave', '波浪', '波浪']},
	{'cross':['cross', '交叉', '交叉']},
	{'high polish':['high polish', '光身', '光身']},
	{'matte':['matte', '噴沙', '噴沙']},
	{'brushed':['brushed', '拉絲', '拉絲']},
	{'hammered':['hammered', '錘面', '錘面']},
	{'milgrain':['milgrain', '珠邊', '珠邊']},
	{'puzzle':['puzzle', '拼合', '拼合']},
	{'forge':['forge', '鍛造', '鍛造']},
	{'angerosa':['angerosa', 'angerosa', 'angerosa']},
	{'feerie ported':['feerie ported', 'feerie ported', 'feerie ported']},
	{'timeless ones':['timeless ones', 'timeless ones', 'timeless ones']},
	{'18KW':['18K White Gold', '18K白金', '18K白金']},
	{'18KY':['18K Yellow Gold', '18K黃金', '18K黃金']},
	{'18KR':['18K Rose Gold', '18K玫瑰', '18K玫瑰']},
	{'18KRG':['18K Rose Gold', '18K玫瑰', '18K玫瑰']},
	{'18K White':['18K White Gold', '18K白金', '18K白金']},
	{'18K Rose Gold':['18K Rose Gold', '18K玫瑰金', '18K玫瑰金']},
	{'PT':['PT', '鉑金', '鉑金']},
	{'PT950/900':['PT', '鉑金', '鉑金']},
	{'Mixed':['Mixed', '混金', '混金']},
	{'Men':['Men', '男士款式', '男士款式']},
	{'Female':['Female', '女士款式', '女士款式']},	
	{'m':['Men', '男士款式', '男士款式']},
	{'f':['Female', '女士款式', '女士款式']},		

	{'unit_price':['unit_price', '價格', '价格']},
	{'metal':['metal', '金屬', '金属']},
	{'sideStone':['side stone','輔石','辅石']},
	{'stock':['stock','款號','款号']},
	{'name':['name','名稱','名称']},
	{'description':['description','詳情描述','详情描述']},

	{'ct':['ct', '重量', '重量']},	
	{'Wedding Ring':['Wedding Ring','結婚對戒','结婚对戒']},
	{'your name':['your name','客人稱呼','客人称呼']},
	{'your Phone No.':['your Phone No.','客人電話號碼','客人电话号码']},	
	{'Appointment':['Appointment','請預約','请预约']},
	{'Details fo Appointment':['Details fo Appointment','預約詳情','预约详情']},
	{'Contact Us':['Contact Us','聯絡我們','联络我们']},

	{'True':['Yes','是','是']},
	{'False':['No','否','否']},
	{'Yes':['Yes','是','是']},
	{'1':['Yes','是','是']},
	{'No':['No','否','否']},	
	{'0':['No','否','否']},
	
]